name: CI

on:
  push:
    branches:
    - master

jobs:
  superlinter:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Lint Code Base
      uses: github/super-linter@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
